name: Deploy ARC runner image

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - element
jobs:
  deploy-docker-arc-runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build docker image
        run: |
          cd runner
          make docker-build-default
          make docker-build-dind
      - name: Push default docker image to ghcr.io
        run: docker push ghcr.io/element-hq/actions-runner:ubuntu-22.04
      - name: Push dind docker image to ghcr.io
        run: docker push ghcr.io/element-hq/actions-runner-dind:ubuntu-22.04
